
language: node_js
node_js:
  - "8.0"
  - "7.0"
  - "6.2.2"
before_script:
  - yarn bootstrap
script:
  - npm test
  - yarn build
  - cd packages/testground
  - yarn crau:build
after_script:
  - yarn global add codecov
  - codecov
